[package]
name = "calc"
version = "0.1.0"
authors = ["Ian Pringle <ipringle2@liberty.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
